baseURL = 'https://github.com/illuHarmolipi/illuHarmolipi.github.io'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'poison'

[module]
  [module.hugoVersion]
    extended = true
    min = '0.135.0'
    

